version: '3.8'
services:
  backend:
    build:
      context: '.'
      dockerfile: Dockerfile.dev
    image: 'biseo/backend-dev'
    container_name: 'biseo-server-dev'
    volumes:
      - './src:/usr/src/app/src'
    ports:
      - '3000:3000'
  database:
    logging: # disable logging
      driver: 'none'
  redis:
    logging: # disable logging
      driver: 'none'
